<a href="https://colab.research.google.com/github/neohack22/BASc/blob/machine_learning/Fitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Train/ Test Split

## import the necessary libraries

### SyntaxError: invalid syntax

In [1]:
# importing the necessary libraries

import pandas as pd
form sklearn import datasets, minear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

SyntaxError: ignored

### End of SyntaxError

### SyntaxError: invalid syntax

In [2]:
# to load and analyze the data files as a Panda data frame
import pandas as pd

# a module to load a sample dataset and a model to run a linear regression
form sklearn import datasets, linear_model

# to split to a training and test sets
from sklearn.model_selection import train_test_split

# to plot graphs of the data
from matplotlib import pyplot as plt

SyntaxError: ignored

### End of SyntaxError

In [0]:
# to load and analyze the data files as a Panda data frame
import pandas as pd

# a module to load a sample dataset and a model to run a linear regression
from sklearn import datasets, linear_model

# to split to a training and a test sets
from sklearn.model_selection import train_test_split

# to plot graphs of the data
from matplotlib import pyplot as plt

## Load the Diabetes dataset

In [0]:
# Declare the columns names
columns = "age sex bmi map tc ldl hdl tch ltg glu".split()

# Call the diabetes dataset from sklearn
diabetes = datasets.load_diabetes()

# load the dataset as a pandas data frame
df = pd.DataFrame(diabetes.data, columns=columns)

# define the target variable (dependent variable) as y
y = diabetes.target

## create training and testing vars

### SyntaxError: Missing parentheses in call to 'print'

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2)
print X_train.shape, y_train.shape
print X_test.shape, y_test.shape

SyntaxError: ignored

### End of SyntaxError

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(353, 10) (353,)
(89, 10) (89,)


## fit a model

In [0]:
lm = linear_model.LinearRegression()

In [0]:
model = lm.fit(X_train, y_train)
predictions = lm.predict(X_test)

In [10]:
# show the 1st 5 predicted values
predictions[0:5]

array([199.72444919, 162.76150779,  80.90135385, 249.79855238,
       139.19449835])

## The line / model

In [11]:
plt.scatter(y_test, predictions)
plt.xlabel("True Values")
plt.ylabel("Predictions")

Text(0, 0.5, 'Predictions')

## print the accuracy score

In [12]:
print("Score:", model.score(X_test, y_test))

Score: 0.5308367967938983


## K-Folds Cross Validation

### NameError: name 'np' is not defined

In [13]:
# import KFold
from sklearn.model_selection import KFold

# create an array
X = np.array([[1, 2], [3, 4], [1, 2]], [3, 4])

# Create another array
y = np.array([1, 2, 3, 4])

# Define the split - into 2 folds
kf = KFold(n_splits=2)

# returns the number of splitting iterations in the cross-validator
kf.get_n_splits(X)

NameError: ignored

## End of NameError

In [0]:
import numpy as np

In [15]:
# import KFold
from sklearn.model_selection import KFold

# create an array
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])

# create another array
y = np.array([1, 2, 3, 4])

# Define the split - into 2 folds
kf = KFold(n_splits=2)

# returns the number of splitting iterations in the cross-validator
kf.get_n_splits(X)

2

In [16]:
print(kf)

KFold(n_splits=2, random_state=None, shuffle=False)


### the folds

In [17]:
for train_index, test_index in kf.split(X):
  print("TRAIN:", train_index, "TEST:", test_index)
  X_train, X_test = X[train_index], X[test_index]
  y_train, y_test = y[train_index], y[test_index]

TRAIN: [2 3] TEST: [0 1]
TRAIN: [0 1] TEST: [2 3]


## Leave One Out Cross Validation

In [18]:
from sklearn.model_selection import LeaveOneOut
X = np.array([[1, 2], [3, 4]])
y = np.array([1, 2])
loo = LeaveOneOut()
loo.get_n_splits(X)

2

In [19]:
for train_index, test_index in loo.split(X):
  print("TRAIN:", train_index, "TEST:", test_index)
  X_train, X_test = X[train_index], X[test_index]
  y_train, y_test = y[train_index], y[test_index]
  print(X_train, X_test, y_train, y_test)

TRAIN: [1] TEST: [0]
[[3 4]] [[1 2]] [2] [1]
TRAIN: [0] TEST: [1]
[[1 2]] [[3 4]] [1] [2]


## Necessary imports

### ModuleNotFoundError

In [20]:
from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn import metrics

ModuleNotFoundError: ignored

### End of ModuleNotFoundError

### SyntaxError: invalid syntax

In [21]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn iport metrics

SyntaxError: ignored

### End of SyntaxError

In [0]:
# renaming + deprecation of cross_validation sub-module to model_selection
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics

## Perform 6-fold cross validation

### y <> diabetes.target

In [23]:
scores = cross_val_score(model, df, y, cv=6)
print("Cross-validated scores:", scores)

ValueError: ignored

In [24]:
scores = cross_val_score(model, np.asarray(df), np.asarray(y), cv=6)
print("Cross-validated scores:", scores)

ValueError: ignored

In [25]:
df_ar = np.asarray(df).reshape(-1,1)
y_a = np.asarray(y)
scores = cross_val_score(model, df_ar, y_a, cv=6)
print("Cross-validated scores:", scores)

ValueError: ignored

In [26]:
y_a.shape

(2,)

In [27]:
y.shape

(2,)

In [28]:
df_ar1 = np.asarray(df).reshape(2,-1)
y_a = np.asarray(y)
scores = cross_val_score(model, df_ar1, y_a, cv=6)
print("Cross-validated scores;", scores)

ValueError: ignored

### y_dt <> y

In [0]:
y_dt = diabetes.target

In [30]:
scores = cross_val_score(model, df, y_dt, cv=6)
print("Cross_validated scores:", scores)

Cross_validated scores: [0.4554861  0.46138572 0.40094084 0.55220736 0.43942775 0.56923406]


# Make cross validated predictions

In [31]:
predictions = cross_val_predict(model, df, y_dt, cv=6)
plt.scatter(y_dt, predictions)

In [32]:
accuracy = metrics.r2_score(y_dt, predictions)
print("Cross-Predicted Accuracy:", accuracy)

Cross-Predicted Accuracy: 0.4908065838640776


cf https://towardsdatascience.com/train-test-split-and-cross-validation-in-python-80b61beca4b6